### ISSUE TITLE
Using subreddits safe?

### ISSUE THREAD

**Issue by ashvinstech** [bimsina/reWalls#8]
Is using subreddits safe like there won't be a wallpaper which will cause any issue or infrig google play's policies ? Some subreddits are - EarthPorn, CityPorn, SkyPorn, WeatherPorn or which came with the app

**Comment by ashvinstech** [comment]
I have also seen some Anime Wallpapers in exact fit section which were too weird

**Comment by bimsina** [comment]
> I have also seen some Anime Wallpapers in exact fit section which were too weird

@ashvinstech The exact fit section searches for your phone's resolution on reddit.
