### ISSUE TITLE
How to display more images in every feed ?

### ISSUE THREAD

**Issue by yashdevelops** [bimsina/reWalls#9]
I just realized that the app shows approx 25 images per feed. How to increase it to show more ? Thank you.
and can you please tell how to add more subreddits ?

**Comment by Virtuoso05** [comment]
Did you findout?

**Comment by yashdevelops** [comment]
> Did you findout?

Yes. But I don't remember it anymore.

**Comment by bimsina** [comment]
This is because I haven't used the official reddit api. I have just appended .json to every url.
If you want more than 25 images, you can use the official reddit api.
